// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package users

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateBusinessParticular(ctx context.Context, arg CreateBusinessParticularParams) (BusinessParticular, error)
	CreatePurchaseRequisition(ctx context.Context, arg CreatePurchaseRequisitionParams) (PurchaseRequisition, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePurchaseRequisition(ctx context.Context, requisitionID uuid.UUID) error
	DeleteUsers(ctx context.Context, userID string) error
	GetPurchaseRequisition(ctx context.Context, requisitionID uuid.UUID) (PurchaseRequisition, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, userID string) (User, error)
	GetUserTypeByID(ctx context.Context, userTypePk int32) (NullUserTypeEnum, error)
	GetUserTypes(ctx context.Context) ([]UserType, error)
	ListPurchaseRequisitions(ctx context.Context) ([]PurchaseRequisition, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateBusinessParticulars(ctx context.Context, arg UpdateBusinessParticularsParams) error
	UpdatePurchaseRequisition(ctx context.Context, arg UpdatePurchaseRequisitionParams) error
	UpdateUsers(ctx context.Context, arg UpdateUsersParams) error
}

var _ Querier = (*Queries)(nil)
