// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: quotationRequest.sql

package users

import (
	"context"

	"github.com/google/uuid"
)

const createQuotationRequest = `-- name: CreateQuotationRequest :one
INSERT INTO quotation_requests (
proposal_request_id, requisition_id, supplier_id, status
) VALUES ($1,$2,$3,$4)
RETURNING proposal_request_id, requisition_id, supplier_id, status, date_submitted, date_approved, date_rejected
`

type CreateQuotationRequestParams struct {
	ProposalRequestID int64     `json:"proposal_request_id"`
	RequisitionID     uuid.UUID `json:"requisition_id"`
	SupplierID        uuid.UUID `json:"supplier_id"`
	Status            string    `json:"status"`
}

func (q *Queries) CreateQuotationRequest(ctx context.Context, arg CreateQuotationRequestParams) (QuotationRequest, error) {
	row := q.db.QueryRow(ctx, createQuotationRequest,
		arg.ProposalRequestID,
		arg.RequisitionID,
		arg.SupplierID,
		arg.Status,
	)
	var i QuotationRequest
	err := row.Scan(
		&i.ProposalRequestID,
		&i.RequisitionID,
		&i.SupplierID,
		&i.Status,
		&i.DateSubmitted,
		&i.DateApproved,
		&i.DateRejected,
	)
	return i, err
}
