// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: Users.sql

package users

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
        user_id,username,password,email,user_typefk
) VALUES ($1,$2,$3,$4,$5)
RETURNING user_id, username, password, email, user_typefk, created_at, updated_at
`

type CreateUserParams struct {
	UserID     string `json:"user_id"`
	Username   string `json:"username"`
	Password   string `json:"password"`
	Email      string `json:"email"`
	UserTypefk int32  `json:"user_typefk"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserID,
		arg.Username,
		arg.Password,
		arg.Email,
		arg.UserTypefk,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.UserTypefk,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUsers = `-- name: DeleteUsers :exec
DELETE FROM users
WHERE user_id = $1
`

func (q *Queries) DeleteUsers(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUsers, userID)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, username, password, email, user_typefk, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.UserTypefk,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, username, password, email, user_typefk, created_at, updated_at FROM users
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.UserTypefk,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserTypeByID = `-- name: GetUserTypeByID :one
SELECT "user_type" FROM "user_types" WHERE "user_type_pk" = $1
`

func (q *Queries) GetUserTypeByID(ctx context.Context, userTypePk int32) (NullUserTypeEnum, error) {
	row := q.db.QueryRow(ctx, getUserTypeByID, userTypePk)
	var user_type NullUserTypeEnum
	err := row.Scan(&user_type)
	return user_type, err
}

const getUserTypes = `-- name: GetUserTypes :many
SELECT "user_type_pk", "user_type" FROM "user_types"
`

func (q *Queries) GetUserTypes(ctx context.Context) ([]UserType, error) {
	rows, err := q.db.Query(ctx, getUserTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserType{}
	for rows.Next() {
		var i UserType
		if err := rows.Scan(&i.UserTypePk, &i.UserType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT user_id, username, password, email, user_typefk, created_at, updated_at FROM users
ORDER BY username
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Password,
			&i.Email,
			&i.UserTypefk,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUsers = `-- name: UpdateUsers :exec
UPDATE users
set username = $2,
    password = $3,
    email= $4,
    user_typefk=$5
WHERE user_id = $1
`

type UpdateUsersParams struct {
	UserID     string `json:"user_id"`
	Username   string `json:"username"`
	Password   string `json:"password"`
	Email      string `json:"email"`
	UserTypefk int32  `json:"user_typefk"`
}

func (q *Queries) UpdateUsers(ctx context.Context, arg UpdateUsersParams) error {
	_, err := q.db.Exec(ctx, updateUsers,
		arg.UserID,
		arg.Username,
		arg.Password,
		arg.Email,
		arg.UserTypefk,
	)
	return err
}
