// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: Users.sql

package users

import (
	"context"
)

const deleteUsers = `-- name: DeleteUsers :exec
DELETE FROM users
WHERE userid = $1
`

func (q *Queries) DeleteUsers(ctx context.Context, userid int32) error {
	_, err := q.db.Exec(ctx, deleteUsers, userid)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT userid, username, password, email, usertypefk, created_at, updated_at FROM users
WHERE userid = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, userid int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, userid)
	var i User
	err := row.Scan(
		&i.Userid,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.Usertypefk,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT userid, username, password, email, usertypefk, created_at, updated_at FROM users
ORDER BY username
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Userid,
			&i.Username,
			&i.Password,
			&i.Email,
			&i.Usertypefk,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUsers = `-- name: UpdateUsers :exec
UPDATE Users
set username = $2,
    password = $3,
    email= $4,
    usertypefk=$5
WHERE userid = $1
`

type UpdateUsersParams struct {
	Userid     int32  `json:"userid"`
	Username   string `json:"username"`
	Password   string `json:"password"`
	Email      string `json:"email"`
	Usertypefk int32  `json:"usertypefk"`
}

func (q *Queries) UpdateUsers(ctx context.Context, arg UpdateUsersParams) error {
	_, err := q.db.Exec(ctx, updateUsers,
		arg.Userid,
		arg.Username,
		arg.Password,
		arg.Email,
		arg.Usertypefk,
	)
	return err
}
